### ISSUE TITLE
Why my transaction and Validator  are NaN

### ISSUE THREAD

**Issue by RockWu1108** [ConsenSys/quorum-explorer#41]
Why do my transactions and validators have errors in the block information?
image url :　[https://ppt.cc/fcR6jx](url)
1.)
 config.json : 
```
{
  "algorithm": "raft",
  "nodes": [
    {
      "name": "rpcnode",
      "client": "goquorum",
      "rpcUrl": "http://xxx.xxx.xxx.xxx:22000",
      "privateTxUrl": ""
    }
  ]
}
```

2.)
env.local : 
```
QE_BASEPATH="/explorer"
QE_CONFIG_PATH="./config.json"
NODE_ENV=development
DISABLE_AUTH=true
NEXTAUTH_URL=http://localhost:25000
NEXTAUTH_URL_INTERNAL=http://localhost:25000
NEXTAUTH_SECRET=d02ea4076f38d5832f37095a17a4021e
```
3.)
docker-compose.yaml

```
services:
   explorer:
      image: consensys/quorum-explorer:latest
      volumes:
      - ./config.json:/app/config.json
      - ./.env.local:/app/.env.production
      ports:
      - 25000:25000/tcp
```
